In [1]:
import math
import torch
from torch import nn

In [3]:
d_model = 10
seq_len = 5

# Create a matrix of shape (seq_len, d_model)
pe = torch.zeros(seq_len, d_model)

print(pe)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [4]:
# Create a vecor of shape (seq_len, 1)
position = torch.arange(0, seq_len, dtype=torch.float).unsqueeze(1)

print(position)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])


In [5]:
div_term = \
    torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

print(div_term)

tensor([1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04])


In [6]:
print(position * div_term)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04],
        [2.0000e+00, 3.1698e-01, 5.0238e-02, 7.9621e-03, 1.2619e-03],
        [3.0000e+00, 4.7547e-01, 7.5357e-02, 1.1943e-02, 1.8929e-03],
        [4.0000e+00, 6.3396e-01, 1.0048e-01, 1.5924e-02, 2.5238e-03]])


In [7]:
# Apply the sin to even positions
pe[:, 0::2] = torch.sin(position * div_term)

# Apply the cos to uneven positions
pe[:, 1::2] = torch.cos(position * div_term)

print(pe)

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
          9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  3.1170e-01,  9.5018e-01,  5.0217e-02,
          9.9874e-01,  7.9621e-03,  9.9997e-01,  1.2619e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  4.5775e-01,  8.8908e-01,  7.5285e-02,
          9.9716e-01,  1.1943e-02,  9.9993e-01,  1.8929e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  5.9234e-01,  8.0569e-01,  1.0031e-01,
          9.9496e-01,  1.5924e-02,  9.9987e-01,  2.5238e-03,  1.0000e+00]])


In [8]:
pe = pe.unsqueeze(0)

print(pe)

tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
           1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
         [ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
           9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00],
         [ 9.0930e-01, -4.1615e-01,  3.1170e-01,  9.5018e-01,  5.0217e-02,
           9.9874e-01,  7.9621e-03,  9.9997e-01,  1.2619e-03,  1.0000e+00],
         [ 1.4112e-01, -9.8999e-01,  4.5775e-01,  8.8908e-01,  7.5285e-02,
           9.9716e-01,  1.1943e-02,  9.9993e-01,  1.8929e-03,  1.0000e+00],
         [-7.5680e-01, -6.5364e-01,  5.9234e-01,  8.0569e-01,  1.0031e-01,
           9.9496e-01,  1.5924e-02,  9.9987e-01,  2.5238e-03,  1.0000e+00]]])


In [46]:
batch = 3
seq_len = 6
d_model = 10
h = 5

x = torch.arange(0, batch*seq_len*d_model)
x = x.view(batch, seq_len, d_model)
x

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]],

        [[120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
         [160, 161, 

In [49]:
x.view(x.shape[0], x.shape[1], h, d_model//h).transpose(1, 2)

tensor([[[[  0,   1],
          [ 10,  11],
          [ 20,  21],
          [ 30,  31],
          [ 40,  41],
          [ 50,  51]],

         [[  2,   3],
          [ 12,  13],
          [ 22,  23],
          [ 32,  33],
          [ 42,  43],
          [ 52,  53]],

         [[  4,   5],
          [ 14,  15],
          [ 24,  25],
          [ 34,  35],
          [ 44,  45],
          [ 54,  55]],

         [[  6,   7],
          [ 16,  17],
          [ 26,  27],
          [ 36,  37],
          [ 46,  47],
          [ 56,  57]],

         [[  8,   9],
          [ 18,  19],
          [ 28,  29],
          [ 38,  39],
          [ 48,  49],
          [ 58,  59]]],


        [[[ 60,  61],
          [ 70,  71],
          [ 80,  81],
          [ 90,  91],
          [100, 101],
          [110, 111]],

         [[ 62,  63],
          [ 72,  73],
          [ 82,  83],
          [ 92,  93],
          [102, 103],
          [112, 113]],

         [[ 64,  65],
          [ 74,  75],
          [ 84, 